### ISSUE TITLE
Highlight Post in phpBB 3.3.0

### ISSUE THREAD

**Issue by Herve-be** [phpBB-Studio/HighlightPosts#4]
**Describe the bug**
At activation time : Erreur AJAX Service Unavailable

**To Reproduce**
1. Go to 'PCA Customise'
2. Click on 'Activate'

This on phpBB 3.3.0 after modifying /ext/threedi/hlposts/ext.php as 3Di told
replace `		if ( !(phpbb_version_compare(PHPBB_VERSION, '3.2.1', '>=') && phpbb_version_compare(PHPBB_VERSION, '3.3.0@dev', '<')) )`
by `		if ( !(phpbb_version_compare(PHPBB_VERSION, '3.2.1', '>=') && phpbb_version_compare(PHPBB_VERSION, '4.0.0@dev', '<')) )`

**Comment by 3D-I** [comment]
You solved already as per: https://www.phpbb.com/community/viewtopic.php?p=15492186#p15492186

Next time close the issue thanks.
